/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customlayoutsample;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JSeparator;
import javax.swing.SwingConstants;

/**
 *
 * @author mahdi
 */
public class CustomLayoutTest extends javax.swing.JFrame {

    /**
     * Creates new form CustomLayoutSample_
     */
    public CustomLayoutTest() {
        initComponents();
        testPanel.setLayout(new VerticalLayout(15));
//        testPanel.setLayout(new HorizontalLayout(15));
        testPanel.setBorder(BorderFactory.createEmptyBorder(50,50,50,50));
        testPanel.add(createButton("1"));
        /*JSeparator sep1 = new JSeparator(SwingConstants.HORIZONTAL);
        sep1.setPreferredSize(new Dimension(35,35));
        sep1.setMinimumSize(new Dimension(35,35));
        sep1.setMaximumSize(new Dimension(35,35));
        sep1.setBackground(Color.RED);
        testPanel.add(sep1);*/
        testPanel.add(createButton("2"));
        testPanel.add(createButton("3"));
        testPanel.add(createButton("4"), (Integer) 100);
        testPanel.add(createButton("5"));
    }
    
    public static JButton createButton(String text)
    {
        JButton b = new JButton(text);  //default preferred size of 35 x 28
//        b.setPreferredSize(new Dimension(35,35));
//        b.setMinimumSize(new Dimension(35,35));
//        b.setMaximumSize(new Dimension(35,35));
//        b.setSize(new Dimension(35,35));
//        b.setVisible(true);
        return b;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));

        testPanel.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(testPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomLayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomLayoutTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel testPanel;
    // End of variables declaration//GEN-END:variables
}
